---
title: Saldae Analytics Daily report
author: Faridh
date: 2020-04-23 13:18
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    theme: sandstone
    favicon: saldae_logo.png
    source_code: embed
params:
  sald_explor_chart: NA
  sald_predict_chart: NA
---
# Saldae {data-navmenu="Intro"}

There should be something written here



`r names(params$sald_explor_chart)[[1]]`
=======================================================================



Column {data-width=600}
-----------------------------------------------------------------------

### Sales Forecast

```{r, warning=FALSE}
params$sald_explor_chart[[1]]

```


### Sales by State

```{r, warning=FALSE}
params$sald_predict_chart[[1]]

```

Column {.tabset data-width=400}
-----------------------------------------------------------------------

### Sales by Category

```{r, warning=FALSE}

params$sald_predict_chart[[1]]

```

### Best Sellers

```{r, warning=FALSE}
targe_variable <- names(params$sald_explor_chart)[1]
```

`r names(params$sald_explor_chart)[[2]]`
=======================================================================



Column {data-width=600}
-----------------------------------------------------------------------

### Sales Forecast

```{r, warning=FALSE}
params$sald_explor_chart[[2]]

```


### Sales by State

```{r, warning=FALSE}
params$sald_predict_chart[[2]]

```

Column {.tabset data-width=400}
-----------------------------------------------------------------------

### Sales by Category

```{r, warning=FALSE}

params$sald_predict_chart[[2]]

```

### Best Sellers

```{r, warning=FALSE}
targe_variable <- names(params$sald_explor_chart)[2]
```

`r names(params$sald_explor_chart)[[3]]`
=======================================================================



Column {data-width=600}
-----------------------------------------------------------------------

### Sales Forecast

```{r, warning=FALSE}
params$sald_explor_chart[[3]]

```


### Sales by State

```{r, warning=FALSE}
params$sald_predict_chart[[3]]

```

Column {.tabset data-width=400}
-----------------------------------------------------------------------

### Sales by Category

```{r, warning=FALSE}

params$sald_predict_chart[[3]]

```

### Best Sellers

```{r, warning=FALSE}
targe_variable <- names(params$sald_explor_chart)[3]
```
